version: '3.1'

services:
  db:
    container_name: linkhub-pg
    image: postgres:alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: linkhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CCiTEDa9
    ports:
      - "5433:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data